// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Duel
{
    public partial class ResultResponse
    {
        public string winner;
        public int yourTime;
        public int opponentTime;
        public bool gameOver;

        [Preserve]
        public ResultResponse ()
        {
        }
    }
}