// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Duel
{
    public partial class JoinGlobalLobbyResponse
    {
        public string LobbyId;
        public string LobbyName;
        public int PlayerCount;
        public bool Success;

        [Preserve]
        public JoinGlobalLobbyResponse ()
        {
        }
    }
}