// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class DuelBindings
    {
        readonly ICloudCodeService k_Service;
        public DuelBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<Duel.JoinGlobalLobbyResponse> JoinGlobalLobby(string username)
        {
            return await k_Service.CallModuleEndpointAsync<Duel.JoinGlobalLobbyResponse>(
                "Duel",
                "JoinGlobalLobby",
                new Dictionary<string, object>()
                {
                    {"username", username},
                });
        }

        public async Task<Duel.HostGameResponse> HostLobby(string gameType)
        {
            return await k_Service.CallModuleEndpointAsync<Duel.HostGameResponse>(
                "Duel",
                "HostLobby",
                new Dictionary<string, object>()
                {
                    {"gameType", gameType},
                });
        }

        public async Task<Duel.JoinGameResponse> JoinLobby(string lobbyCode, string gameType)
        {
            return await k_Service.CallModuleEndpointAsync<Duel.JoinGameResponse>(
                "Duel",
                "JoinLobby",
                new Dictionary<string, object>()
                {
                    {"lobbyCode", lobbyCode},
                    {"gameType", gameType},
                });
        }

        public async Task<Duel.QuickMatchResponse> QuickMatch(string gameType)
        {
            return await k_Service.CallModuleEndpointAsync<Duel.QuickMatchResponse>(
                "Duel",
                "QuickMatch",
                new Dictionary<string, object>()
                {
                    {"gameType", gameType},
                });
        }

        public async Task<Duel.ResultResponse> SubmitReflexResult(string sessionId, int reactionTimeMs)
        {
            return await k_Service.CallModuleEndpointAsync<Duel.ResultResponse>(
                "Duel",
                "SubmitReflexResult",
                new Dictionary<string, object>()
                {
                    {"sessionId", sessionId},
                    {"reactionTimeMs", reactionTimeMs},
                });
        }
    }
}
