// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Duel
{
    public partial class UgsResponse
    {
        public string LobbyID;
        public string LobbyCode;
        public string LobbyName;
        public bool IsHost;
        public int PlayerCount;
        public bool Success;

        [Preserve]
        public UgsResponse ()
        {
        }
    }
}