// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class DuelBindings
    {
        readonly ICloudCodeService k_Service;
        public DuelBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<Duel.UgsResponse> HostLobby(string gameType, string userName)
        {
            return await k_Service.CallModuleEndpointAsync<Duel.UgsResponse>(
                "Duel",
                "HostLobby",
                new Dictionary<string, object>()
                {
                    {"gameType", gameType},
                    {"userName", userName},
                });
        }

        public async Task<Duel.UgsResponse> JoinLobby(string lobbyCode, string userName)
        {
            return await k_Service.CallModuleEndpointAsync<Duel.UgsResponse>(
                "Duel",
                "JoinLobby",
                new Dictionary<string, object>()
                {
                    {"lobbyCode", lobbyCode},
                    {"userName", userName},
                });
        }

        public async Task<Duel.UgsResponse> LeaveLobby(string lobbyId)
        {
            return await k_Service.CallModuleEndpointAsync<Duel.UgsResponse>(
                "Duel",
                "LeaveLobby",
                new Dictionary<string, object>()
                {
                    {"lobbyId", lobbyId},
                });
        }

        public async Task<Duel.UgsResponse> QuickMatch(string gameType, string userName)
        {
            return await k_Service.CallModuleEndpointAsync<Duel.UgsResponse>(
                "Duel",
                "QuickMatch",
                new Dictionary<string, object>()
                {
                    {"gameType", gameType},
                    {"userName", userName},
                });
        }

        public async Task SubmitReflexResult(string lobbyId, int reactionTimeMs, string playerName)
        {
            await k_Service.CallModuleEndpointAsync(
                "Duel",
                "SubmitReflexResult",
                new Dictionary<string, object>()
                {
                    {"lobbyId", lobbyId},
                    {"reactionTimeMs", reactionTimeMs},
                    {"playerName", playerName},
                });
        }
    }
}
