// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.Duel
{
    public partial class QuickMatchResponse
    {
        public string Session;
        public string OpponentId;
        public bool IsHost;

        [Preserve]
        public QuickMatchResponse ()
        {
        }
    }
}