name: Deploy WebGL Build

on:
  push:
    branches: [ master ]
    paths:
      - 'WebGLBuild/**' 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: Deploy to Server
        run: |
          rsync -avz --delete WebGLBuild/ phil@3.99.70.5:~/projects/Duel/Duel-WebGL/
